from studieadviestext import *


print(STUDIEDOKTER_TITEL)
OPTIES = "Kies 0: altijd; 1: vaak; 2: regelmatig; 3: soms; 4: nooit"
input_AANTAL_WEKEN_VRAAG = int(input(f'{AANTAL_WEKEN_VRAAG}\n'))
print (OPTIES)
input_COMPETENTIE_STELLING_1 = input(f'{COMPETENTIE_STELLING_1}\n')
print (OPTIES)
input_COMPETENTIE_STELLING_2 = input(f'{COMPETENTIE_STELLING_2}\n')
print (OPTIES)
input_COMPETENTIE_STELLING_3 = input(f'{COMPETENTIE_STELLING_3}\n')
print (OPTIES)
input_COMPETENTIE_STELLING_4 = input(f'{COMPETENTIE_STELLING_4}\n')
print (OPTIES)
input_COMPETENTIE_STELLING_5 = input(f'{COMPETENTIE_STELLING_5}\n')

if input_AANTAL_WEKEN_VRAAG >= 10:
    print (OPTIES)
    input_COMPETENTIE_STELLING_6 = input(f'{COMPETENTIE_STELLING_6}\n')
    print (OPTIES)
    input_COMPETENTIE_STELLING_7 = input(f'{COMPETENTIE_STELLING_7}\n')

if input_AANTAL_WEKEN_VRAAG >=10:
    GEMIDDELDE_SCORE = int(input_COMPETENTIE_STELLING_1 + input_COMPETENTIE_STELLING_2 + input_COMPETENTIE_STELLING_3 + input_COMPETENTIE_STELLING_4 + input_COMPETENTIE_STELLING_5 + input_COMPETENTIE_STELLING_6 + input_COMPETENTIE_STELLING_7) /7
else:
    GEMIDDELDE_SCORE = int(input_COMPETENTIE_STELLING_1 + input_COMPETENTIE_STELLING_2 + input_COMPETENTIE_STELLING_3 + input_COMPETENTIE_STELLING_4 + input_COMPETENTIE_STELLING_5)/5



if GEMIDDELDE_SCORE <= 2:
    print (COMPETENTIE_ADVIES_TITEL)
    print(COMPETENTIE_ADVIES_ZORGELIJK)
elif GEMIDDELDE_SCORE <= 3:
    print (COMPETENTIE_ADVIES_TITEL)
    print (COMPETENTIE_ADVIES_TWIJFELACHTIG)
else:
    print(COMPETENTIE_ADVIES_TITEL)
    print(COMPETENTIE_ADVIES_GERUSTSTELLEND)